### ISSUE TITLE
YAML syntax for changing bounds / confusion with tighten/loosen

### ISSUE THREAD

**Issue by msarahan** [conda-forge/conda-forge-repodata-patches-feedstock#1003]
### Comment:

In #998, I was clearly confused regarding the workings of loosen_depends and tighten_depends. The functionality feels especially conflated when used with upper_bound. It seems like I'm not the only one, with @isuruf mixing things up in #994.

I am NOT proposing removing loosen_depends and tighten_depends. I think there's too many existing YAML specs that already use them. I would like to propose a new key at the level of loosen_depends and tighten_depends, though: `change_depends`

Schema:
```
then:
  change_depends:
    lower_bound: <str>, evaluates as >=str
    upper_bound: <str>, evaluates as <str
    exclusions: <list[str]>, evaluates as comma-separated != constraints, with wildcard suffixes where not provided
```

I would also deprecate the use of upper_bound and lower_bound with loosen_depends and tighten_depends, and codify loosen_depends and tighten_depends only as relative operations on the current bounds.

@beckermr, @jaimergp - it seems like you two are the main instigators on the YAML stuff (which I very much like, by the way). Thoughts? If this seems helpful, I can take on implementing it.
