### ISSUE TITLE
Possible to patch version number?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/conda-forge-repodata-patches-feedstock#899]
### Comment:

Hi. Is it possible to patch the version number of a release of a package? (e.g. there is an extra character that got into a SemVer package version that shouldn't be there and is confusing solvers). If so, it is unclear how to do it from the [`then` section in the `recipe/README.md`](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/46cc6140f782c0605d48994b6de283c3d37debd9/recipe/README.md#L72).

I think I need a patch along the lines of the following, but I don't know the proper keyword to use to overwrite the version

```yaml
if:
  name: sherpa
  version: v2.2.16
then:
  - replace_???:  # what key should be used here
      old: ${version}
      new: 2.2.16
````
